import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';import{OrbitControls}from'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js';
const ds=[['夏','约前2070—前1600'],['商','约前1600—前1046'],['西周','前1046—前771'],['春秋战国','前770—前221'],['秦','前221—前206'],['汉','前202—220'],['三国两晋南北朝','220—589'],['隋','581—618'],['唐','618—907'],['宋','960—1279'],['元','1271—1368'],['明','1368—1644'],['清','1644—1912']];
const info={秦:['公元前221—前206年','秦朝统一',['建立第一个统一的多民族国家','推行郡县制','统一文字、货币、度量衡','修筑长城、驰道']],汉:['公元前202—220年','汉代文明',['丝绸之路沟通东西方','休养生息促进经济发展','统一多民族国家进一步发展']],唐:['618—907年','盛唐气象',['长安是国际性大都会','科举制进一步发展','诗歌书法绘画成就突出']],宋:['960—1279年','宋代社会',['商品经济活跃','活字印刷术等科技发展','海外贸易繁荣']],明:['1368—1644年','明代社会',['郑和下西洋','北京城建设','文学艺术繁荣']],清:['1644—1912年','清代疆域',['统一多民族国家进一步巩固','边疆治理制度完善']]};
let scene,camera,renderer,controls,objs=[],ray,mouse;const canvas=document.querySelector('#world');
function init(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(7,5,9);renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});controls=new OrbitControls(camera,canvas);controls.enableDamping=true;scene.add(new THREE.AmbientLight(0x9bbcff,2));let l=new THREE.DirectionalLight(0xffffff,3);l.position.set(6,9,7);scene.add(l);ray=new THREE.Raycaster();mouse=new THREE.Vector2();canvas.onclick=pick;build('秦');loop()}
function M(c){return new THREE.MeshStandardMaterial({color:c,roughness:.7})}function B(n,x,y,z,a,b,c,m){let o=new THREE.Mesh(new THREE.BoxGeometry(a,b,c),m);o.position.set(x,y,z);o.userData.n=n;objs.push(o);scene.add(o)}
function clear(){objs=[];while(scene.children.length>2)scene.remove(scene.children.at(-1))}
function build(n){clear();if(n==='秦'){let stone=M(0x806c55),gold=M(0xc49b52),terr=M(0xa87c58),wall=M(0x8c8f87);B('咸阳宫',0,1.5,0,5,3,3,stone);for(let x=-2;x<=2;x++)B('宫殿立柱',x,1.4,1.65,.3,2.8,.3,gold);B('宫殿屋顶',0,3.25,0,5.8,.35,3.8,M(0x28333d));for(let z=-4;z<=4;z+=.8)B('长城',-6,1,z,.7,1.2,.5,wall);B('驰道',0,.05,4,10,.1,1.3,M(0x6f5a45));for(let r=0;r<3;r++)for(let c=0;c<6;c++)B('兵马俑',-2.5+c*.9,.45,-3+r*.75,.35,.8,.35,terr);B('秦始皇',6,.8,-1,.65,1.5,.45,gold)}else{let m=M(0x6b6570);B(n+'宫殿',0,1.5,0,5,3,3,m);B('城市街道',0,.05,4,10,.1,1.4,M(0x625248));for(let i=-3;i<=3;i++)B('城市建筑',i*1.2,.8,-3,.9,1.6,.9,m)}}
function pick(e){let r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);let h=ray.intersectObjects(objs)[0];if(h){let n=h.object.userData.n;let map={咸阳宫:['咸阳宫','秦都建设体现中央政权与都城建设。'],长城:['万里长城','秦统一后连接、修缮北方长城。'],兵马俑:['秦始皇陵兵马俑','展现秦代雕塑与军事组织的历史信息。'],秦始皇:['秦始皇','嬴政完成统一后建立秦朝并推行一系列统一措施。'],驰道:['驰道','道路网络便于交通、政令和军事行动。']};let x=map[n]||[n,'继续观察这个历史对象的位置、功能与时代背景。'];card(x[0],x[1])}}
function card(t,p){document.querySelector('#cardTitle').textContent=t;document.querySelector('#cardText').textContent=p}
function select(n){document.querySelectorAll('.dynasty').forEach(x=>x.classList.toggle('active',x.dataset.n===n));let d=info[n]||info.秦;document.querySelector('#title').textContent=n+(n==='秦'?' · 咸阳':' · 文明场景');document.querySelector('#period').textContent=d[0];document.querySelector('#cardTitle').textContent=d[1];document.querySelector('#cardText').textContent='拖动 3D 场景探索历史对象。';document.querySelector('#facts').innerHTML=d[2].map(x=>`<div class="fact">◆ ${x}</div>`).join('');document.querySelector('#mission').textContent='找出三个与'+n+'时代相关的历史元素，并说明其作用。';build(n)}
ds.forEach(d=>{let b=document.createElement('button');b.className='dynasty';b.dataset.n=d[0];b.textContent=d[0]+' '+d[1];b.onclick=()=>select(d[0]);document.querySelector('#dynasties').append(b)});init();select('秦');function loop(){requestAnimationFrame(loop);controls.update();renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();renderer.render(scene,camera)}
document.querySelector('#start').onclick=()=>document.querySelector('#timeline').scrollIntoView({behavior:'smooth'});const quiz=[['秦统一后推行的措施不包括？',['统一文字','统一货币','统一度量衡','废除郡县制'],3],['兵马俑主要与谁相关？',['秦始皇','汉武帝','唐太宗','明成祖'],0]];let q=document.querySelector('#quiz');quiz.forEach((a,i)=>{let d=document.createElement('div');d.className='q';d.innerHTML=`<b>${i+1}. ${a[0]}</b>`+a[1].map((x,j)=>`<button class="opt" data-i="${i}" data-j="${j}">${x}</button>`).join('');q.append(d)});q.onclick=e=>{if(e.target.classList.contains('opt'))e.target.classList.add(+e.target.dataset.j===quiz[+e.target.dataset.i][2]?'ok':'bad')};